name: Skygramm_CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build image
        run: docker build -t ${{ secret.IMAGE_TAG }}:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: login docker
        run: docker login -u ${{ secret.DOCKER_USER }} -p ${{ secret.DOCKER_PASSWORD }}
      - name: push image
        run: docker push ${{ secret.IMAGE_TAG }}:$GITHUB_REF_NAME-$GITHUB_RUN_ID